### PR TITLE
Range requests

### PR DESCRIPTION
**Pull request by lastmjs**

### CODE REVIEW

**Comment by lastmjs** [comment]
I'm still cleaning up a  bit and doing some testing, but I would love to get feedback. Besides minor cleanup and some possibly optional features missing as described here https://github.com/dfinity/certified-assets/issues/10, I am done with the implementation of range requests

**Comment by lastmjs** [comment]
I see there have been some major changes to the repo, where is this new `ic-certified-assets` repo so I can get my changes in there?

**Comment by jplevyak** [comment]
It is in cdk-rs.  Please move your PR over there. Thanx!

**Comment by jplevyak** [comment]
Patching this PR into cdk-rs should go smoothly.  If you have any issues feel free to ping me.

**Comment by lastmjs** [comment]
I've moved the PR to the cdk-rs repo: https://github.com/dfinity/cdk-rs/pull/199

**Pull request closed without merging**
